language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install -y pycodestyle
    - conda install -y python-dateutil
    - conda install --yes python=3.6

script:
  - pycodestyle binary_tree.py
  - conda install -c conda-forge time
  - python test_binary_tree.py
  - git hash-tables-ellenwaddle update --init
  - git avl_tree update --init 


# python insert_key_value_pairs.py --struct tree --dataset small_database.txt --number_of_keys 10
